name: CI/CD Python Application

on:
 push:
 workflow_dispatch:

jobs:
 ci-cd:
  runs-on: ubuntu-latest
  env:
   DOCKER_IMAGE: marimuthup04/marimuthudockrepo
   
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4.2.2
 
    - name: Login to Docker
      uses: docker/login-action@v3.3.0
      with:
       username: ${{vars.DOCKER_HUB_USERNAME}}
       password: ${{secrets.DOCKER_HUB}}
   
    - name: Build docker image
      run: |
       docker build -t $DOCKER_IMAGE:1.1 .
       docker tag $DOCKER_IMAGE:1.1 $DOCKER_IMAGE:v1.1
       
    - name: Push docker image
      run: |
       docker push $DOCKER_IMAGE:1.1
       docker push $DOCKER_IMAGE:v1.1

   
      
           
    - name: Setup Kubectl for kubernetes
      uses: azure/setup-kubectl@v3
      with:
       version: 'latest'
    - name: Setup Minikube
      run: |
       minikube start
       kubectl config use-context minikube
       
    - name: Deploy to Kubernetes
      run: |
       kubectl apply  -f k8s/deployment.yml
       kubectl apply -f k8s/service.yml
      
      
      
       
      
   
        
          
       
       
       
        
      
